# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('urlLink', models.CharField(max_length=500)),
                ('descriptionFileLink', models.CharField(max_length=200)),
                ('completed', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
